# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: 0.0.{build}

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\PSScriptAnalyzer -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\Pester -> appveyor.yml

shallow_clone: true
  
environment:
  environment: master
  version: 0.0.$(appveyor_build_number)

matrix:
  fast_finish: true

build_script:
# grab appveyor lab files and needed requirements for tests in CI
- ps: .\build\appveyor.prep.ps1

test_script:
# Test with PowerShell and Pester
- ps: .\build\appveyor.pester.ps1

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))